---
- name: Copy certificates
  copy:
    src: "{{ work_dir }}/{{ item }}.pem"
    dest: "~{{ ansible_user }}/"
  loop:
    - ca
    - ca-key
    - kubernetes
    - kubernetes-key
    - service-account
    - service-account-key

- name: Copy kube config files
  copy:
    src: "{{ work_dir }}/{{ item }}.kubeconfig"
    dest: "~{{ ansible_user }}/"
  loop:
    - admin
    - kube-controller-manager
    - kube-scheduler