---
- copy:
    src: "{{ certs_path }}/{{ item }}.pem"
    dest: "~{{ ansible_user }}/"
  loop:
    - ca
    - ca-key
    - kubernetes
    - kubernetes-key
    - service-account
    - service-account-key
