---
- tempfile:
    state: directory
    prefix: ansible-tmp
  register: tmp_path

- debug:
    msg: "{{ tmp_path.path }}"


- copy:
    src: "{{ item }}"
    dest: "{{ tmp_path.path }}/{{ item }}"
  loop:
    - ca-config.json
    - ca-csr.json

- shell: "cfssl gencert -initca ca-csr.json | cfssljson -bare ca"
  args:
    chdir: "{{ tmp_path.path }}"

- copy:
    src: "{{ item }}"
    dest: "{{ tmp_path.path }}/{{ item }}"
  loop:
    - admin-csr.json

- shell: "cfssl gencert \
            -ca=ca.pem \
            -ca-key=ca-key.pem \
            -config=ca-config.json \
            -profile=kubernetes \
            admin-csr.json | cfssljson -bare admin"
  args:
    chdir: "{{ tmp_path.path }}"