---
- hosts: localhost
  tasks:
    - import_role:
        name: local

- hosts: workers
  tasks:
    - import_role:
        name: worker
      vars:
        work_dir: "{{ hostvars.localhost.work_dir }}"

- hosts: masters
  vars:
    etcd_version: "3.3.9"
  tasks:
    - import_role:
        name: master
      vars:
        work_dir: "{{ hostvars.localhost.work_dir }}"
