---
- hosts: localhost
  tasks:
    - import_role:
        name: local

- hosts: workers
  tasks:
    - import_role:
        name: worker

- hosts: masters
  vars:
    etcd_version: "3.3.9"
  tasks:
    - import_role:
        name: master
